### ISSUE TITLE
Package doesn't install on Ubuntu 14.04

### ISSUE THREAD

**Issue by shaharmor** [kaltura/nginx-vod-module#103]
Hi,

Trying to install your module on Ubuntu 14.04, after install nginx 1.9.1 using the following command:

`apt-get install kaltura-nginx` results in the following error:

```
apt-get install -y kaltura-nginx
Reading package lists... Done
Building dependency tree
Reading state information... Done
kaltura-nginx is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 12 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up kaltura-nginx (1.8.0-1+b2) ...
 System start/stop links for /etc/init.d/kaltura-nginx already exist.
chown: missing operand after ‘/opt/kaltura/log/nginx’
Try 'chown --help' for more information.



		Archving logs to /opt/kaltura/log/log_14_06_15_06_22.tar.gz...
cp: cannot stat ‘/opt/kaltura/log/*log’: No such file or directory
dpkg: error processing package kaltura-nginx (--configure):
 subprocess installed post-installation script returned error exit status 11
Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
Errors were encountered while processing:
 kaltura-nginx
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Any ideas?

**Comment by shaharmor** [comment]
This is another error that appeared after trying to install the module:

```
apt-get install -y kaltura-nginx
Reading package lists... Done
Building dependency tree
Reading state information... Done
kaltura-nginx is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 12 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up kaltura-nginx (1.8.0-1+b2) ...
 System start/stop links for /etc/init.d/kaltura-nginx already exist.
ERROR: could not find /etc/kaltura.d/system.ini so, exiting..
dpkg: error processing package kaltura-nginx (--configure):
 subprocess installed post-installation script returned error exit status 2
Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
Errors were encountered while processing:
 kaltura-nginx
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

I bypassed it by manually creating an empty file at `/etc/kaltura.d/system.ini`, but i'm not sure this is the way its supposed to be. (Obviously the file shouldn't be empty...)

**Comment by kaltura-hooks** [comment]
Hi @shaharmor,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please
ensure that your issue includes the following (please comment with more info if you have not included all this info in
your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
	
	\# rpm -qa "kaltura*"
	
	For deb based systems:
	
	\# dpkg -l "kaltura-*"

 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:

	\# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"

   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
forum.kaltura.org

Thank you in advance,

**Comment by jessp01** [comment]
Hello,

Thank you for your report.
Package has been fixed, reason for the issue was it depended on files from kaltura-base which is not really needed when install kaltura-nginx as a standalone server.

Please run:
\# apt-get update
\# apt-cache policy kaltura-nginx
Make sure the output finds:
Candidate: 1.8.0-2+b2

Then upgrade with:
\# apt-get install kaltura-nginx 

Should be good, please let me know:)

**Comment by shaharmor** [comment]
Just ran apt-get update, but apt-cache policy kaltura-nginx shows:

# apt-cache policy kaltura-nginx
kaltura-nginx:
  Installed: 1.8.0-1+b2
  Candidate: 1.8.0-1+b2
  Version table:
 *** 1.8.0-1+b2 0
        500 http://installrepo.kaltura.org/repo/apt/debian/ jupiter/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by jessp01** [comment]
That means the CDN hasn't updated yet.
You can avoid the wait by changing /etc/apt/sources.list.d/kaltura.list to 
read:
deb [arch=amd64] http://installrepo.origin.kaltura.org/repo/apt/debian jupiter main

That means you will be pulling directly from the CDN origin which is 
updated.

Later, please change back as in general, you would like to pull from CDN.

Thanks,

May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
virtualconnect.kaltura.com

**Comment by shaharmor** [comment]
Still not working:

apt-get install kaltura-nginx
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 kaltura-nginx : PreDepends: kaltura-ffmpeg but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by jessp01** [comment]
Please try
# apt-get install kaltura-ffmpeg

and check why the policy prevents it from being installed so we can better 
understand the issue.

Also, note that you do not need the 'nginx' package installed at all.
While it does not conflict with the kaltura-nginx one, it is also not 
needed for it.
Since Nginx does not support DSO, unlike say, Apache, the kaltura-nginx 
package includes a full version of Nginx.



May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
virtualconnect.kaltura.com

**Comment by shaharmor** [comment]
Tried installing kaltura-ffmpeg:

apt-get install kaltura-ffmpeg
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 kaltura-ffmpeg : Depends: libfdk-aac0 but it is not installable
                  Depends: libfaac0 but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by KalturaCommunity** [comment]
libfdk-aac0 is an official package from the Ubuntu repo:

# apt-cache policy libfdk-aac0
libfdk-aac0:
   Installed: 0.1.2-1
   Candidate: 0.1.2-1
   Version table:
  *** 0.1.2-1 0
         500 http://archive.ubuntu.com/ubuntu/ trusty/multiverse amd64 
Packages
         100 /var/lib/dpkg/status

Try installing it manually and check why APT says it cannot install it.


May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
virtualconnect.kaltura.com

**Comment by shaharmor** [comment]
Apparently GCE doesn't install the multiverse repositories by default. After adding them manually it seems to work.

Thanks a lot!

**Comment by jessp01** [comment]
Great, please close the issue. Will add a note to the README about needing 
multiverse.

Thanks,

May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
virtualconnect.kaltura.com

**Comment by shaharmor** [comment]
Does this module includes the kaltura API? what should i write in the upstream part of the nginx conf? localhost:88?

**Comment by jessp01** [comment]
No, it does not. For integration with the Kaltura server, you will need to install kaltura-server. It can be installed on the same machine or on a separate one.
See:
https://github.com/kaltura/platform-install-packages/blob/master/doc/install-kaltura-deb-based.md

**Comment by gelbander** [comment]
@shaharmor "Apparently GCE doesn't install the multiverse repositories by default. After adding them manually it seems to work."

How do you manually add multiverse and where?

**Comment by shaharmor** [comment]
@gelbander 
`echo "deb http://gce.clouds.archive.ubuntu.com/ubuntu/ trusty multiverse" > /etc/apt/sources.list.d/multiverse.list`

then `apt-get update`
